{
  "openapi" : "3.0.3",
  "info" : {
    "contact" : {
      "email" : "blah+oapicf@cliffano.com",
      "name" : "OpenAPI Clients Factory",
      "url" : "https://github.com/oapicf/pinterest-sdk"
    },
    "description" : "Pinterest's REST API",
    "license" : {
      "name" : "MIT",
      "url" : "https://spdx.org/licenses/MIT"
    },
    "termsOfService" : "https://developers.pinterest.com/terms/",
    "title" : "Pinterest REST API",
    "version" : "5.6.0"
  },
  "servers" : [ {
    "url" : "https://api.pinterest.com/v5"
  } ],
  "tags" : [ {
    "description" : "View analytical information about advertising.\n\n\nNote: If the current operation_user_account (defined by the access token)\nhas access to another user's Ad Accounts via\n<a href='/docs/reference/business-access/'>Pinterest Business Access</a>,\nyou can modify your request to use the current operation_user_account's\npermissions to those Ad Accounts by including the ad_account_id in the path\nparameters for the request (e.g. .../?ad_account_id=12345&...).",
    "name" : "ad_accounts"
  }, {
    "description" : "View, create or update ad groups.",
    "name" : "ad_groups"
  }, {
    "description" : "View, create or update ads.",
    "name" : "ads"
  }, {
    "description" : "View, create, or update audiences.",
    "name" : "audiences"
  }, {
    "description" : "View audience insights.",
    "name" : "audience_insights"
  }, {
    "description" : "View, create, update, or delete information about boards.",
    "name" : "boards"
  }, {
    "description" : "Create, update, or download ads-related entities in bulk.",
    "name" : "bulk"
  }, {
    "description" : "View, create or update campaigns.",
    "name" : "campaigns"
  }, {
    "description" : "Manage information about shopping product catalogs and items.",
    "name" : "catalogs"
  }, {
    "description" : "Submit conversion events via the Pinterest API.",
    "name" : "conversion_events"
  }, {
    "description" : "View, create, or update conversion tags.",
    "name" : "conversion_tags"
  }, {
    "description" : "View, create, or update customer lists.",
    "name" : "customer_lists"
  }, {
    "description" : "View, create or update keywords.",
    "name" : "keywords"
  }, {
    "description" : "Register and manage media uploads.",
    "name" : "media"
  }, {
    "description" : "Generating and refreshing OAuth access tokens.",
    "name" : "oauth"
  }, {
    "description" : "View order lines.",
    "name" : "order_lines"
  }, {
    "description" : "View, create, update, or delete information about Pins.",
    "name" : "pins"
  }, {
    "description" : "Product Group Promotion",
    "name" : "product_group_promotions"
  }, {
    "description" : "View, create or update resources.",
    "name" : "resources"
  }, {
    "description" : "Get related and suggested terms.",
    "name" : "terms"
  }, {
    "description" : "Get Terms Of Service",
    "name" : "terms_of_service"
  }, {
    "description" : "Read-only information about user accounts associated with a given access token.",
    "name" : "user_account"
  } ],
  "paths" : {
    "/oauth/token" : {
      "post" : {
        "description" : "Generate an OAuth access token by using an authorization code or a refresh token.\n\nSee <a href='/docs/getting-started/authentication/'>Authentication</a> for more.",
        "operationId" : "oauth/token",
        "security" : [ {
          "basic" : [ ]
        } ],
        "summary" : "Generate OAuth access token",
        "tags" : [ "oauth" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account" : {
      "get" : {
        "description" : "Get account information for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/reference/business-access/'>Understanding Business Access</a> for more information.",
        "operationId" : "user_account/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/analytics" : {
      "get" : {
        "description" : "Get analytics for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/analytics/top_pins" : {
      "get" : {
        "description" : "Gets analytics data about a user's top pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics/top_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get user account top pins analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/analytics/top_video_pins" : {
      "get" : {
        "description" : "Gets analytics data about a user's top video pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics/top_video_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get user account top video pins analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/pins" : {
      "post" : {
        "description" : "Create a Pin on a board or board section owned by the \"operation user_account\".\n\nNote: If the current \"operation user_account\" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).\n\n- This function i[...]",
        "operationId" : "pins/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Create Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/pins/{pin_id}" : {
      "delete" : {
        "description" : "Delete a Pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "pins/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Delete Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the[...]",
        "operationId" : "pins/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/pins/{pin_id}/save" : {
      "post" : {
        "description" : "Save a pin on a board or board section owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "pins/save",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Save pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/pins/{pin_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=\"https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list\">List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do t[...]",
        "operationId" : "pins/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin analytics",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/boards" : {
      "get" : {
        "description" : "Get a list of the boards owned by the \"operation user_account\" + group boards where this account is a collaborator\n\nOptional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.\n- If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.",
        "operationId" : "boards/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "List boards",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}" : {
      "delete" : {
        "description" : "Delete a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a board owned by the operation user_account - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "Get board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a board owned by the \"operating user_account\".",
        "operationId" : "boards/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections" : {
      "get" : {
        "description" : "Get a list of all board sections from a board owned by the \"operation user_account\" - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "List board sections",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}" : {
      "delete" : {
        "description" : "Delete a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board section of a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/media" : {
      "get" : {
        "description" : "List media uploads filtered by given parameters.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/list",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "List media uploads",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Register your intent to upload media\n\nThe response includes all of the information needed to upload the media\nto Pinterest.\n\nTo upload the media, make an HTTP POST request (using <tt>curl</tt>, for\nexample) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header\nvalue. Send the media file's contents as the request's <tt>file</tt>\nparameter and also include all of the parameters from\n<tt>upload_parameters</tt>.\n\n<strong><a href='/docs/solutions/content-ap[...]",
        "operationId" : "media/create",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "pins:write" ]
        } ],
        "summary" : "Register media upload",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "disabled"
      }
    },
    "/media/{media_id}" : {
      "get" : {
        "description" : "Get details for a registered media upload, including its current status.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/get",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "Get media upload details",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts" : {
      "get" : {
        "description" : "Get a list of the ad_accounts that the \"operation user_account\" has access to.\n- This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>.",
        "operationId" : "ad_accounts/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad accounts",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.\nAn ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account. <p/>\nYou can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.) <p/>\nFor more, see <a class=\"reference external\" href=\"https:/[...]",
        "operationId" : "ad_accounts/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}" : {
      "get" : {
        "description" : "Get an ad account",
        "operationId" : "ad_accounts/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ad_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad account analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more ads. For the requested ad(s) and metrics,\nthe response will include the requested metric information (e.g. SPEND_IN_DOLLAR) for the requested target type\n(e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage[...]",
        "operationId" : "ad_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns" : {
      "get" : {
        "description" : "Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "campaigns/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple ad campaigns based on campaign_ids. <p/>\n<strong>Note:</strong><p/>\n- <p>The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser’s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser’s profil[...]",
        "operationId" : "campaigns/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new campaigns. Every campaign has its own campaign_id and houses one or more ad groups, which contain one or more ads.\nFor more, see <a href=\"https://help.pinterest.com/en/business/article/set-up-your-campaign/\">Set up your campaign</a>. <p/>\n<strong>Note:</strong>\n- The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used[...]",
        "operationId" : "campaigns/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/{campaign_id}" : {
      "get" : {
        "description" : "Get a specific campaign given the campaign ID.",
        "operationId" : "campaigns/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get campaign",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "campaigns/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get campaign analytics",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more campaigns.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-an[...]",
        "operationId" : "campaign_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more ad groups.\nFor the requested ad group(s) and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/shar[...]",
        "operationId" : "ad_groups_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups" : {
      "get" : {
        "description" : "List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id. Do not provide both.",
        "operationId" : "ad_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple existing ad groups.",
        "operationId" : "ad_groups/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new ad groups. All ads in a given ad group will have the same budget, bid, run dates, targeting, and placement (search, browse, other). For more information, <a href=\"https://help.pinterest.com/en/business/article/campaign-structure\" target=\"_blank\"> click here</a>.</p>\n<strong>Note:</strong>\n- 'bid_in_micro_currency' and 'budget_in_micro_currency' should be expressed in microcurrency amounts based on the currency field set in the advertiser's profi[...]",
        "operationId" : "ad_groups/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}" : {
      "get" : {
        "description" : "Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will\ncontain additional information from the Ad Review process.\nFor more information about our policies and rejection reasons see the <a href=\"https://www.pinterest.com/_/_/policy/advertising-guidelines/\"\ntarget=\"_blank\">Pinterest advertising standards</a>.",
        "operationId" : "ad_groups/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad group",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ad_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad group analytics",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads" : {
      "get" : {
        "description" : "List ads that meet the filters provided:\n  - Listed campaign ids or ad group ids or ad ids\n  - Listed entity statuses <p/>\nIf no filter is provided, all ads in the ad account are returned. <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>\nReview status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.\nFor more, see <a href=\"[...]",
        "operationId" : "ads/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple existing ads",
        "operationId" : "ads/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new ads. Request must contain ad_group_id, creative_type, and the source Pin pin_id.",
        "operationId" : "ads/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/{ad_id}" : {
      "get" : {
        "description" : "Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will\ncontain additional information from the Ad Review process.\nFor more information about our policies and rejection reasons see the <a href=\"https://www.pinterest.com/_/_/policy/advertising-guidelines/\"\ntarget=\"_blank\">Pinterest advertising standards</a>.",
        "operationId" : "ads/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ads/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad analytics",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_previews" : {
      "post" : {
        "description" : "Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>\nIf you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href=\"https://help.pinterest.com/en/business/article/promoted-pins-overview\" target=\"_blank\">Ads Overview</a>.) <p/>\nYou can view the returned preview URL on[...]",
        "operationId" : "ad_previews/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad preview with pin or image",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bid_floor" : {
      "post" : {
        "description" : "List bid floors for your campaign configuration. Bid floors are given in microcurrency values based on the currency in the bid floor specification. <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser’s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser’s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars as an example currency:</p>\n<ul>\[...]",
        "operationId" : "ad_groups_bid_floor/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get bid floors",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/events" : {
      "post" : {
        "description" : "The Pinterest API offers advertisers a way to send Pinterest their conversion information (including web conversions, in-app conversions, or even offline conversions) based on their <code>ad_account_id</code>. The request body should be a JSON object.\n- This endpoint requires an <code>access_token</code> be generated through Ads Manager. Review the <a href=\"/docs/conversions/conversion-management/#Authenticating%20for%20the%20Conversion%20Tracking%20endpoint\">Conversi[...]",
        "operationId" : "events/create",
        "security" : [ {
          "conversion_token" : [ ]
        } ],
        "summary" : "Send conversion events to the Pinterest API for Conversions",
        "tags" : [ "conversion_events" ],
        "x-ratelimit-category" : "ads_conversions",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "product_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get product group analytics",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/reports" : {
      "get" : {
        "description" : "This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report and it's valid for an hour.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager."[...]",
        "operationId" : "analytics/get_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get the account analytics report created by the async call",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Bus[...]",
        "operationId" : "analytics/create_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Create async request for an account analytics report",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences" : {
      "get" : {
        "description" : "Get list of audiences for the ad account.",
        "operationId" : "audiences/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List audiences",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create an audience you can use in targeting for specific ad groups. Targeting combines customer information with\nthe ways users interact with Pinterest to help you reach specific groups of users; you can include or exclude\nspecific audience_ids when you create an ad group. <p/>\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>.",
        "operationId" : "audiences/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/{audience_id}" : {
      "get" : {
        "description" : "Get a specific audience given the audience ID.",
        "operationId" : "audiences/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update (edit or remove) an existing targeting audience.",
        "operationId" : "audiences/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists" : {
      "get" : {
        "description" : "<p>Get a set of customer lists including id and name based on the filters provided.</p>\n<p>(Customer lists are a type of audience.) For more information, see\n<a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\n or the <a href=\"/docs/ads/targeting/#Audiences\" target=\"_blank\">Audiences</a>\nsection of the ads management guide.</p>",
        "operationId" : "customer_lists/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get customer lists",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "<p>Create a customer list from your records(hashed or plain-text email addresses, or hashed MAIDs or IDFAs).</p>\n<p>A customer list is one of the four types of Pinterest audiences: for more information, see <a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\nor the <a href=\"/docs/ads/targeting/#Audiences\" target=\"_blank\">Audiences</a> section of the ads management guide.<p/>\n<p><b>Please review our[...]",
        "operationId" : "customer_lists/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create customer lists",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}" : {
      "get" : {
        "description" : "Gets a specific customer list given the customer list ID.",
        "operationId" : "customer_lists/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get customer list",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "<p>Append or remove records to/from an existing customer list. (A customer list is one of the four types of Pinterest audiences.)</p>\n<p>When you add records to an existing customer list, the system scans the additions for existing Pinterest\naccounts; those are the records that will be added to your “CUSTOMER_LIST” audience. Your original list of records\nto add will be deleted when the matching process is complete.</p>\n<p>For more information, see <a href=\"https://h[...]",
        "operationId" : "customer_lists/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update customer list",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords" : {
      "get" : {
        "description" : "<p>Get a list of keywords based on the filters provided.</p><p>For more information, see <a target=\"_blank\" href=\"https://help.pinterest.com/en/business/article/keyword-targeting\">Keyword targeting</a>.</p>\n<p><b>Notes:</b></p> <ul style=\"list-style-type: square;\"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more information on match types,[...]",
        "operationId" : "keywords/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "<p>Update one or more keywords' bid and archived fields.</p> <p>Archiving a keyword effectively deletes it - keywords no longer receive metrics and no longer visible within the parent entity's keywords list.</p>",
        "operationId" : "keywords/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "<p>Create keywords for following entity types(advertiser, campaign, ad group or ad).</p> <p>For more information, see <a target=\"_blank\" href=\"https://help.pinterest.com/en/business/article/keyword-targeting\">Keyword targeting</a>.</p>\n<p><b>Notes:</b></p> <ul style=\"list-style-type: square;\"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For mor[...]",
        "operationId" : "keywords/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords/metrics" : {
      "get" : {
        "description" : "See keyword metrics for a specified country, aggregated across all of Pinterest.\n(Definitions are available from the \"Get delivery metrics definitions\"\n<a href=\"/docs/api/v5/#operation/delivery_metrics/get\">API endpoint</a>).",
        "operationId" : "country_keywords_metrics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get country's keyword metrics",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions" : {
      "patch" : {
        "description" : "Update multiple existing Product Group Promotions (by product_group_id)",
        "operationId" : "product_group_promotions/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update product group promotions",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Add one or more product groups from your catalog to an existing ad group. (Product groups added to an ad group are a 'product group promotion.')",
        "operationId" : "product_group_promotions/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create product group promotions",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}" : {
      "get" : {
        "description" : "Get a product group promotion by id",
        "operationId" : "product_group_promotion/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get a product group promotion by id",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for an ad account.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage[...]",
        "operationId" : "ad_account_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for an ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/terms/suggested" : {
      "get" : {
        "description" : "Get popular search terms that begin with your input term. <p/>\nExample: 'sport' would return popular terms like 'sports bar' and 'sportswear', but not 'motor sports' since the phrase does not begin with the given term.",
        "operationId" : "terms_suggested/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List suggested terms",
        "tags" : [ "terms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/terms_of_service" : {
      "get" : {
        "description" : "Get the text of the terms of service and see whether the advertiser has accepted the terms of service.",
        "operationId" : "terms_of_service/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get terms of service",
        "tags" : [ "terms_of_service" ],
        "x-sandbox" : "enabled",
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/download" : {
      "post" : {
        "description" : "Create an asynchronous report that may include information on campaigns, ad groups, product groups, ads,\nand/or keywords; can filter by campaigns. Though the entities may be active, archived, or paused,\nonly active entities will return data.",
        "operationId" : "bulk_download/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get advertiser entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/upsert" : {
      "post" : {
        "description" : "Either create or update any combination of campaigns, ad groups, product groups, ads, or keywords.\nNote that this request will be processed asynchronously; the response will include a <code>request_id</code>\nthat can be used to obtain the status of the request.",
        "operationId" : "bulk_upsert/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create/update ad entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/{bulk_request_id}" : {
      "get" : {
        "description" : "Get the status of a bulk request by <code>request_id</code>, along with a download URL that will allow you to download the\nnew or updated entity data (campaigns, ad groups, product groups, ads, or keywords).",
        "operationId" : "bulk_request/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Download advertiser entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/feeds" : {
      "get" : {
        "description" : "Fetch feeds owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/business[...]",
        "operationId" : "feeds/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List feeds",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create a new feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/bu[...]",
        "operationId" : "feeds/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Create feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/feeds/{feed_id}" : {
      "delete" : {
        "description" : "Delete a feed owned by the \"operating user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busine[...]",
        "operationId" : "feeds/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Delete feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get a single feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/bu[...]",
        "operationId" : "feeds/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update a feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busine[...]",
        "operationId" : "feeds/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Update feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/feeds/{feed_id}/processing_results" : {
      "get" : {
        "description" : "Fetch a feed processing results owned by the \"operation user_account\". Please note that for now the bookmark parameter is not functional and only the first page will be available until it is implemented in some release in the near future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use[...]",
        "operationId" : "feed_processing_results/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List processing results for a given feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/processing_results/{processing_result_id}/item_issues" : {
      "get" : {
        "description" : "List item validation issues for a given feed processing result owned by the \"operation user_account\". Please note that for now query parameters 'item_numbers' and 'item_validation_issue' cannot be used simultaneously until it is implemented in some release in the future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/l[...]",
        "operationId" : "items_issues/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List item issues for a given processing result",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/items" : {
      "get" : {
        "description" : "Get the items of the catalog owned by the \"operation user_account\". <a href=\"/docs/shopping/catalog/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation use[...]",
        "operationId" : "items/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/items/batch/{batch_id}" : {
      "get" : {
        "description" : "Get a single catalogs items batch owned by the \"operating user_account\". <a href=\"/docs/shopping/catalog/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operatio[...]",
        "operationId" : "items_batch/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items batch",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/items/batch" : {
      "post" : {
        "description" : "This endpoint supports multiple operations on a set of one or more catalog items owned by the \"operation user_account\". <a href=\"/docs/shopping/catalog/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use[...]",
        "operationId" : "items_batch/post",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Operate on item batch",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/products/get_by_product_group_filters" : {
      "post" : {
        "description" : "List products Pins owned by the \"operation user_account\" that meet the criteria specified in the Catalogs Product Group Filter given in the request.\n- This endpoint has been implemented in POST to allow for complex filters. This specific POST endpoint is designed to be idempotent.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad[...]",
        "operationId" : "products_by_product_group_filter/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "catalogs:read", "pins:read" ]
        } ],
        "summary" : "List filtered products",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}" : {
      "delete" : {
        "description" : "Delete a product group owned by the \"operation user_account\" from being in use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href[...]",
        "operationId" : "catalogs_product_groups/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Delete product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get a singe product group for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the follow[...]",
        "operationId" : "catalogs_product_groups/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update product group owned by the \"operation user_account\" to use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://he[...]",
        "operationId" : "catalogs_product_groups/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Update product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/products" : {
      "get" : {
        "description" : "Get a list of product pins for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the follo[...]",
        "operationId" : "catalogs_product_group_pins/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "catalogs:read", "pins:read" ]
        } ],
        "summary" : "List products",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/product_counts" : {
      "get" : {
        "description" : "Get a product counts for a given Catalogs Product Group owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a h[...]",
        "operationId" : "catalogs_product_groups/product_counts_get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get product counts",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/product_groups" : {
      "get" : {
        "description" : "Get a list of product groups for a given Catalogs Feed Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a[...]",
        "operationId" : "catalogs_product_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List product groups",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create product group to use in Catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://he[...]",
        "operationId" : "catalogs_product_groups/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Create product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "disabled"
      }
    },
    "/resources/ad_account_countries" : {
      "get" : {
        "description" : "Get Ad Accounts countries",
        "operationId" : "ad_account_countries/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad accounts countries",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/delivery_metrics" : {
      "get" : {
        "description" : "Get the definitions for the delivery metrics available for synchronous or asynchronous reports.",
        "operationId" : "delivery_metrics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read", "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get available delivery metrics' definitions",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/metrics_ready_state" : {
      "get" : {
        "description" : "Learn whether conversion or non-conversion metrics are finalized and ready to query.",
        "operationId" : "metrics_ready_state/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get metrics ready state",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/targeting/interests/{interest_id}" : {
      "get" : {
        "description" : "<p>Get details of a specific interest given interest ID.</p> <p>Click <a href=\"https://docs.google.com/spreadsheets/d/1HxL-0Z3p2fgxis9YBP2HWC3tvPrs1hAuHDRtH-NJTIM/edit#gid=118370875\" target=\"_blank\">here</a> for a spreadsheet listing interests and their IDs.</p>",
        "operationId" : "interest_targeting_options/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get interest details",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/targeting/{targeting_type}" : {
      "get" : {
        "description" : "<p>You can use targeting values in ads placement to define your intended audience. </p> <p>Targeting metrics are organized around targeting specifications.</p> <p>For more information on ads targeting, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>.</p>\n<p><b>Sample return:</b></p> <pre class=\"literal-block\"> [{&quot;36313&quot;: &quot;Australia: Moreton Bay - Nort[...]",
        "operationId" : "targeting_options/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting options",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/terms/related" : {
      "get" : {
        "description" : "Get a list of terms logically related to each input term. <p/>\nExample: the term 'workout' would list related terms like 'one song workout', 'yoga workout', 'workout motivation', etc.",
        "operationId" : "terms_related/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List related terms",
        "tags" : [ "terms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "pinterest_oauth2" : {
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://www.pinterest.com/oauth/",
            "scopes" : {
              "ads:read" : "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write" : "Create, update, or delete ads, ad groups, campaigns etc.",
              "boards:read" : "See your public boards, including group boards you join",
              "boards:read_secret" : "See your secret boards",
              "boards:write" : "Create, update, or delete your public boards",
              "boards:write_secret" : "Create, update, or delete your secret boards",
              "catalogs:read" : "See all of your catalogs data",
              "catalogs:write" : "Create, update, or delete your catalogs data",
              "pins:read" : "See your public Pins",
              "pins:read_secret" : "See your secret Pins",
              "pins:write" : "Create, update, or delete your public Pins",
              "pins:write_secret" : "Create, update, or delete your secret Pins",
              "user_accounts:read" : "See your user accounts and followers",
              "user_accounts:write" : "Update your user accounts and followers"
            },
            "tokenUrl" : "https://api.pinterest.com/v5/oauth/token"
          }
        },
        "type" : "oauth2"
      },
      "conversion_token" : {
        "description" : "This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).",
        "scheme" : "bearer",
        "type" : "http"
      },
      "basic" : {
        "scheme" : "basic",
        "type" : "http"
      }
    }
  }
}