{
  "openapi" : "3.0.3",
  "info" : {
    "contact" : {
      "email" : "blah+oapicf@cliffano.com",
      "name" : "OpenAPI Clients Factory",
      "url" : "https://github.com/oapicf/pinterest-sdk"
    },
    "description" : "Pinterest's REST API",
    "license" : {
      "name" : "MIT",
      "url" : "https://spdx.org/licenses/MIT"
    },
    "termsOfService" : "https://developers.pinterest.com/terms/",
    "title" : "Pinterest REST API",
    "version" : "5.14.0"
  },
  "servers" : [ {
    "url" : "https://api.pinterest.com/v5"
  } ],
  "tags" : [ {
    "description" : "View analytical information about advertising.\n\n\nNote: If the current operation_user_account (defined by the access token)\nhas access to another user's Ad Accounts via\n<a href='/docs/getting-started/using-business-access/'>Pinterest Business Access</a>,\nyou can modify your request to use the current operation_user_account's\npermissions to those Ad Accounts by including the ad_account_id in the path\nparameters for the request (e.g. .../?ad_account_id=12345&...).",
    "name" : "ad_accounts"
  }, {
    "description" : "View, create or update ad groups.",
    "name" : "ad_groups"
  }, {
    "description" : "View, create or update ads.",
    "name" : "ads"
  }, {
    "description" : "View, create, or update advanced auction item bid options.",
    "name" : "advanced_auction"
  }, {
    "description" : "View audience insights.",
    "name" : "audience_insights"
  }, {
    "description" : "View, share, or revoke shared audiences.<br>\nAudience Sharing endpoints are not available to all apps,\nif you are interested in using them, reach out to us on our help center page.\n<a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.",
    "name" : "audience_sharing"
  }, {
    "description" : "View, create, or update audiences.",
    "name" : "audiences"
  }, {
    "description" : "View, create, or update information related to billing.",
    "name" : "billing"
  }, {
    "description" : "View, create, update, or delete information about boards.",
    "name" : "boards"
  }, {
    "description" : "Create, update, or download ads-related entities in bulk.",
    "name" : "bulk"
  }, {
    "description" : "View, create or update campaigns.",
    "name" : "campaigns"
  }, {
    "description" : "Manage information about shopping product catalogs and items.",
    "name" : "catalogs"
  }, {
    "description" : "Submit conversion events via the Pinterest API.",
    "name" : "conversion_events"
  }, {
    "description" : "View, create, or update conversion tags.",
    "name" : "conversion_tags"
  }, {
    "description" : "View, create, or update customer lists.",
    "name" : "customer_lists"
  }, {
    "description" : "View, create, or update commerce integrations.",
    "name" : "integrations"
  }, {
    "description" : "View, create or update keywords.",
    "name" : "keywords"
  }, {
    "description" : "View, create, or update lead ads.",
    "name" : "lead_ads"
  }, {
    "description" : "View lead forms.",
    "name" : "lead_forms"
  }, {
    "description" : "Create and export leads information from lead ads.",
    "name" : "leads_export"
  }, {
    "description" : "Register and manage media uploads.",
    "name" : "media"
  }, {
    "description" : "Generate and refresh OAuth access tokens.",
    "name" : "oauth"
  }, {
    "description" : "View order lines.",
    "name" : "order_lines"
  }, {
    "description" : "View, create, update, or delete information about Pins.",
    "name" : "pins"
  }, {
    "description" : "View, create, update, or delete information about promoted product groups.",
    "name" : "product_group_promotions"
  }, {
    "description" : "View metadata about available metrics and targeting options in the Pinterest API.",
    "name" : "resources"
  }, {
    "description" : "Search for Pins and boards owned by the current user.",
    "name" : "search"
  }, {
    "description" : "View, create or update targeting templates.",
    "name" : "targeting_template"
  }, {
    "description" : "View related and suggested terms for ads targeting.",
    "name" : "terms"
  }, {
    "description" : "View Advertising Terms Of Service.",
    "name" : "terms_of_service"
  }, {
    "description" : "View user accounts associated with a given access token.",
    "name" : "user_account"
  } ],
  "paths" : {
    "/ad_accounts" : {
      "get" : {
        "description" : "Get a list of the ad_accounts that the \"operation user_account\" has access to.\n- This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>.",
        "operationId" : "ad_accounts/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad accounts",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.\nAn ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account. <p/>\nYou can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.) <p/>\nFor more, see <a class=\"reference external\" href=\"https:/[...]",
        "operationId" : "ad_accounts/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}" : {
      "get" : {
        "description" : "Get an ad account",
        "operationId" : "ad_accounts/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups" : {
      "get" : {
        "description" : "List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id. Do not provide both.",
        "operationId" : "ad_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple existing ad groups.",
        "operationId" : "ad_groups/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new ad groups. All ads in a given ad group will have the same budget, bid, run dates, targeting, and placement (search, browse, other). For more information, <a href=\"https://help.pinterest.com/en/business/article/campaign-structure\" target=\"_blank\"> click here</a>.</p>\n<strong>Note:</strong>\n- 'bid_in_micro_currency' and 'budget_in_micro_currency' should be expressed in microcurrency amounts based on the currency field set in the advertiser's profi[...]",
        "operationId" : "ad_groups/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, the furthest back you can a[...]",
        "operationId" : "ad_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad group analytics",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more ad groups.\nFor the requested ad group(s) and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/shar[...]",
        "operationId" : "ad_groups_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for ad groups",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/audience_sizing" : {
      "post" : {
        "description" : "Get potential audience size for an ad group with given targeting criteria. \nPotential audience size estimates the number of people you may be able to reach per month with your campaign. \nIt is based on historical advertising data and the targeting criteria you select.\nIt does not guarantee results or take into account factors such as bid, budget, schedule, seasonality or product experiments.",
        "operationId" : "ad_groups/audience_sizing",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get audience sizing",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}" : {
      "get" : {
        "description" : "Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will\ncontain additional information from the Ad Review process.\nFor more information about our policies and rejection reasons see the <a href=\"https://www.pinterest.com/_/_/policy/advertising-guidelines/\" target=\"_blank\">Pinterest advertising standards</a>.",
        "operationId" : "ad_groups/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad group",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_previews" : {
      "post" : {
        "description" : "Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>\nIf you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href=\"https://help.pinterest.com/en/business/article/promoted-pins-overview\" target=\"_blank\">Ads Overview</a>.) <p/>\nYou can view the returned preview URL on[...]",
        "operationId" : "ad_previews/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ad preview with pin or image",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads" : {
      "get" : {
        "description" : "List ads that meet the filters provided:\n  - Listed campaign ids or ad group ids or ad ids\n  - Listed entity statuses <p/>\nIf no filter is provided, all ads in the ad account are returned. <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>\nReview status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.\nFor more, see <a href=\"[...]",
        "operationId" : "ads/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple existing ads",
        "operationId" : "ads/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new ads. Request must contain ad_group_id, creative_type, and the source Pin pin_id.",
        "operationId" : "ads/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- The request must contain either ad_ids or both campaign_ids a[...]",
        "operationId" : "ads/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad analytics",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads_credit/discounts" : {
      "get" : {
        "description" : "Returns the list of discounts applied to the account.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "ads_credits_discounts/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read", "billing:read" ]
        } ],
        "summary" : "Get ads credit discounts",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads_credit/redeem" : {
      "post" : {
        "description" : "Redeem ads credit on behalf of the ad account id and apply it towards billing.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "ads_credit/redeem",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write", "billing:write" ]
        } ],
        "summary" : "Redeem ad credits",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more ads. For the requested ad(s) and metrics,\nthe response will include the requested metric information (e.g. SPEND_IN_DOLLAR) for the requested target type\n(e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage[...]",
        "operationId" : "ad_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for ads",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/{ad_id}" : {
      "get" : {
        "description" : "Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will\ncontain additional information from the Ad Review process.\nFor more information about our policies and rejection reasons see the <a href=\"https://www.pinterest.com/_/_/policy/advertising-guidelines/\" target=\"_blank\">Pinterest advertising standards</a>.",
        "operationId" : "ads/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad",
        "tags" : [ "ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, the furthest back you can are allowed to pull data is [...]",
        "operationId" : "ad_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad account analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audience_insights" : {
      "get" : {
        "description" : "Get Audience Insights for an ad account. The response will return insights for 3 types of audiences: the\nad account's engaged audience on Pinterest, the ad account's total audience on Pinterest and Pinterest's\ntotal audience.<p/>\n<a href=\"https://help.pinterest.com/en/business/article/audience-insights\" target=\"_blank\">Learn more about Audience Insights</a>.",
        "operationId" : "audience_insights/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get audience insights",
        "tags" : [ "audience_insights" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences" : {
      "get" : {
        "description" : "Get list of audiences for the ad account.",
        "operationId" : "audiences/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List audiences",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create an audience you can use in targeting for specific ad groups. Targeting combines customer information with\nthe ways users interact with Pinterest to help you reach specific groups of users; you can include or exclude\nspecific audience_ids when you create an ad group. <p/>\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>.",
        "operationId" : "audiences/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/{audience_id}" : {
      "get" : {
        "description" : "Get a specific audience given the audience ID.",
        "operationId" : "audiences/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update (edit or remove) an existing targeting audience.",
        "operationId" : "audiences/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/custom" : {
      "post" : {
        "description" : "Create a custom audience and find the audiences you want your ads to reach.",
        "operationId" : "audiences/create_custom",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create custom audience",
        "tags" : [ "audiences" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/shared/accounts" : {
      "get" : {
        "description" : "List all ad accounts and/or businesses that have access to a specific audience. The audience must be owned by the requesting ad account.",
        "operationId" : "ad_accounts_audiences_shared_accounts/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List accounts with access to an audience owned by an ad account",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/ad_accounts/shared" : {
      "patch" : {
        "description" : "From an ad account, share a specific audience with another ad account, or revoke access to a previously shared audience. Only the audience owner account can share the audience. The recipient ad account(s) must be in the same <a href='https://help.pinterest.com/en/business/article/create-and-manage-accounts'>Pinterest Business Hierarchy</a> as the business owner of the ad account.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/beta-and-advan[...]",
        "operationId" : "update_ad_account_to_ad_account_shared_audience",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update audience sharing between ad accounts",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/businesses/shared" : {
      "patch" : {
        "description" : "From an ad account, share a specific audience with a business account, or revoke access to a previously shared audience. Only the audience owner account can share the audience. The recipient business account must be in the same business hierarchy as the business owner of the ad account.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.",
        "operationId" : "update_ad_account_to_business_shared_audience",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update audience sharing from an ad account to businesses",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bid_floor" : {
      "post" : {
        "description" : "List bid floors for your campaign configuration. Bid floors are given in microcurrency values based on the currency in the bid floor specification. <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser’s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser’ s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars as an example currency:</p>\n<ul>[...]",
        "operationId" : "ad_groups_bid_floor/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get bid floors",
        "tags" : [ "ad_groups" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/billing_profiles" : {
      "get" : {
        "description" : "Get billing profiles in the advertiser account.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "billing_profiles/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read", "billing:read" ]
        } ],
        "summary" : "Get billing profiles",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/download" : {
      "post" : {
        "description" : "Create an asynchronous report that may include information on campaigns, ad groups, product groups, ads,\nand/or keywords; can filter by campaigns. Though the entities may be active, archived, or paused,\nonly active entities will return data.",
        "operationId" : "bulk_download/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get advertiser entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/upsert" : {
      "post" : {
        "description" : "Either create or update any combination of campaigns, ad groups, product groups, ads, or keywords.\nNote that this request will be processed asynchronously; the response will include a <code>request_id</code>\nthat can be used to obtain the status of the request.",
        "operationId" : "bulk_upsert/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create/update ad entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/{bulk_request_id}" : {
      "get" : {
        "description" : "Get the status of a bulk request by <code>request_id</code>, along with a download URL that will allow you to download the\nnew or updated entity data (campaigns, ad groups, product groups, ads, or keywords).",
        "operationId" : "bulk_request/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Download advertiser entities in bulk",
        "tags" : [ "bulk" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns" : {
      "get" : {
        "description" : "Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "campaigns/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update multiple ad campaigns based on campaign_ids. <p/>\n<strong>Note:</strong><p/>\n - <p>The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser’s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser’ s prof[...]",
        "operationId" : "campaigns/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create multiple new campaigns. Every campaign has its own campaign_id and houses one or more ad groups, which contain one or more ads.\nFor more, see <a href=\"https://help.pinterest.com/en/business/article/set-up-your-campaign/\">Set up your campaign</a>. <p/>\n<strong>Note:</strong>\n- The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used[...]",
        "operationId" : "campaigns/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, the furthest back you can a[...]",
        "operationId" : "campaigns/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get campaign analytics",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for one or more campaigns.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-an[...]",
        "operationId" : "campaign_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for campaigns",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/{campaign_id}" : {
      "get" : {
        "description" : "Get a specific campaign given the campaign ID.",
        "operationId" : "campaigns/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get campaign",
        "tags" : [ "campaigns" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags" : {
      "get" : {
        "description" : "List conversion tags associated with an ad account.",
        "operationId" : "conversion_tags/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get conversion tags",
        "tags" : [ "conversion_tags" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create a conversion tag, also known as <a href=\"https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag\" target=\"_blank\">Pinterest tag</a>, with the option to enable enhanced match.<p/>\nThe Pinterest Tag tracks actions people take on the ad account’ s website after they view the ad account's ad on Pinterest. The advertiser needs to customize this tag to track conversions.<p/>\nFor more information, see:<p/>\n<a class=\"reference external\" href=\"htt[...]",
        "operationId" : "conversion_tags/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create conversion tag",
        "tags" : [ "conversion_tags" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_write"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/ocpm_eligible" : {
      "get" : {
        "description" : "Get Ocpm eligible conversion tag events for an ad account.",
        "operationId" : "ocpm_eligible_conversion_tags/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get Ocpm eligible conversion tags",
        "tags" : [ "conversion_tags" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/page_visit" : {
      "get" : {
        "description" : "Get all page visit conversion tag events for an ad account.",
        "operationId" : "page_visit_conversion_tags/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get page visit conversion tags",
        "tags" : [ "conversion_tags" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/{conversion_tag_id}" : {
      "get" : {
        "description" : "Get information about an existing conversion tag.",
        "operationId" : "conversion_tags/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get conversion tag",
        "tags" : [ "conversion_tags" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists" : {
      "get" : {
        "description" : "<p>Get a set of customer lists including id and name based on the filters provided.</p>\n<p>(Customer lists are a type of audience.) For more information, see\n<a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\n or the <a href=\"/docs/api-features/targeting-overview/\" target=\"_blank\">Audiences</a>\nsection of the ads management guide.</p>",
        "operationId" : "customer_lists/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get customer lists",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "<p>Create a customer list from your records(hashed or plain-text email addresses, or hashed MAIDs or IDFAs).</p>\n<p>A customer list is one of the four types of Pinterest audiences: for more information, see <a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\nor the <a href=\"/docs/api-features/targeting-overview/\" target=\"_blank\">Audiences</a> section of the ads management guide.<p/>\n <p><b>Please r[...]",
        "operationId" : "customer_lists/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create customer lists",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}" : {
      "get" : {
        "description" : "Gets a specific customer list given the customer list ID.",
        "operationId" : "customer_lists/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get customer list",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "<p>Append or remove records to/from an existing customer list. (A customer list is one of the four types of Pinterest audiences.)</p>\n<p>When you add records to an existing customer list, the system scans the additions for existing Pinterest\naccounts; those are the records that will be added to your “CUSTOMER_LIST” audience. Your original list of records\n to add will be deleted when the matching process is complete.</p>\n<p>For more information, see <a href=\"https://[...]",
        "operationId" : "customer_lists/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update customer list",
        "tags" : [ "customer_lists" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/events" : {
      "post" : {
        "description" : "The Pinterest API offers advertisers a way to send Pinterest their conversion information (including web conversions, in-app conversions, or even offline conversions) based on their <code>ad_account_id</code>. The request body should be a JSON object.\n- This endpoint requires an <code>access_token</code> be generated through Ads Manager. Review the <a href=\"/docs/api-features/conversion-overview/\">Conversions Guide</a> for more details. (Note that the authorization he[...]",
        "operationId" : "events/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        }, {
          "conversion_token" : [ ]
        } ],
        "summary" : "Send conversions",
        "tags" : [ "conversion_events" ],
        "x-ratelimit-category" : "ads_conversions",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/insights/audiences" : {
      "get" : {
        "description" : "Get the scope and type of available audiences, which along with a date, is an audience that has recently had an interaction (referred to here as a type) on pins. Interacted pins can belong to at least the most common **partner** or **Pinterest** scopes. This means that user interactions made on advertiser or partner pins will have the **partner** scope. You can also have user interactions performed in general on Pinterest with the **Pinterest** scope. In that case, you c[...]",
        "operationId" : "audience_insights_scope_and_type/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get audience insights scope and type",
        "tags" : [ "audience_insights" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords" : {
      "get" : {
        "description" : "<p>Get a list of keywords based on the filters provided. If no filter is provided, it will default to the ad_account_id filter, which means it will only return keywords that specifically have parent_id set to the ad_account_id. Note: Keywords can have ad_account_ids, campaign_ids, and ad_group_ids set as their parent_ids. Keywords created through Ads Manager will have their parent_id set to an ad_group_id, not ad_account_id.</p>\n<p>For more information, see <a target=\"[...]",
        "operationId" : "keywords/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "<p>Update one or more keywords' bid and archived fields.</p> <p>Archiving a keyword effectively deletes it - keywords no longer receive metrics and no longer visible within the parent entity's keywords list.</p>",
        "operationId" : "keywords/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "<p>Create keywords for following entity types(advertiser, campaign, ad group or ad).</p> <p>For more information, see <a target=\"_blank\" href=\"https://help.pinterest.com/en/business/article/keyword-targeting\">Keyword targeting</a>.</p>\n<p><b>Notes:</b></p> <ul style=\"list-style-type: square;\"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For mor[...]",
        "operationId" : "keywords/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords/metrics" : {
      "get" : {
        "description" : "See keyword metrics for a specified country, aggregated across all of Pinterest.\n(Definitions are available from the \"Get delivery metrics definitions\"\n<a href=\"/docs/api/v5/#operation/delivery_metrics/get\">API endpoint</a>).",
        "operationId" : "country_keywords_metrics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get country's keyword metrics",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms" : {
      "get" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nList lead forms associated with an ad account ID.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "operationId" : "lead_forms/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List lead forms",
        "tags" : [ "lead_forms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nUpdate lead forms. Lead ads help you reach people who are actively looking for, and interested in, your goods and services. The lead form can be associated with an ad to allow people to fill out the form.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/busin[...]",
        "operationId" : "lead_forms/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update lead forms",
        "tags" : [ "lead_forms" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_write"
      },
      "post" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nCreate lead forms. Lead forms are used in lead ads and allow you to control what text appears on the lead form’ s description, questions and confirmation sections.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "operationId" : "lead_forms/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create lead forms",
        "tags" : [ "lead_forms" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_write"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}" : {
      "get" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nGets a lead form given it's ID. It must also be associated with the provided ad account ID.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "operationId" : "lead_form/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get lead form by id",
        "tags" : [ "lead_forms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}/test" : {
      "post" : {
        "description" : "Create lead form test data based on the list of answers provided as part of the body.\n- List of answers should follow the questions creation order.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "lead_form_test/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create lead form test data",
        "tags" : [ "lead_forms" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads/subscriptions" : {
      "get" : {
        "description" : "Get the advertiser's list of lead ads subscriptions.\n- Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "ad_accounts_subscriptions/get_list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get lead ads subscriptions",
        "tags" : [ "lead_ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create a lead ads webhook subscription.\nSubscriptions allow Pinterest to deliver lead data from Ads Manager directly to the subscriber. Subscriptions can exist for a specific lead form or at ad account level.\n- Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n- Advertisers can set up multiple integrations using ad_account_id + lead_form_id but only one integration per unique records.\n- For data security, egress lead data is encrypted with AES-2[...]",
        "operationId" : "ad_accounts_subscriptions/post",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create lead ads subscription",
        "tags" : [ "lead_ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads/subscriptions/{subscription_id}" : {
      "delete" : {
        "description" : "Delete an existing lead ads webhook subscription by ID.\n- Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "ad_accounts_subscriptions/del_by_id",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Delete lead ads subscription",
        "tags" : [ "lead_ads" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get a specific lead ads subscription record.\n- Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "ad_accounts_subscriptions/get_by_id",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get lead ads subscription",
        "tags" : [ "lead_ads" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads_export" : {
      "post" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nCreate an export of leads collected from a lead ad. This returns a lead_export_id  token that you can use to download the export when it is ready.\n\nNote: Lead ad data will be available up to 30 days after the lead has been submitted.\n\nFor more, see <a class=\"reference external\" href=\"http[...]",
        "operationId" : "leads_export/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create a request to export leads collected from a lead ad",
        "tags" : [ "leads_export" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_write"
      }
    },
    "/ad_accounts/{ad_account_id}/leads_export/{leads_export_id}" : {
      "get" : {
        "description" : "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nGet the export of leads collected from a lead ad. This returns a URL to a list of lead export given a lead_export_id token returned from the create a lead export call. You can use the URL to download the report.\n\nNote: Lead ad data will be available up to 30 days after the lead has been submit[...]",
        "operationId" : "leads_export/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get the lead export from the lead export create call",
        "tags" : [ "leads_export" ],
        "x-sandbox" : "disabled",
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/mmm_reports" : {
      "get" : {
        "description" : "Get an mmm report for an ad account. This returns a URL to an mmm metrics report given a token returned from the\ncreate mmm report endpoint.",
        "operationId" : "analytics/get_mmm_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get advertiser Marketing Mix Modeling (MMM) report.",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "This creates an asynchronous mmm report based on the given request. It returns a token that you can use to download\nthe report when it is ready. NOTE: An additional limit of 5 queries per minute per advertiser applies to this endpoint while it's in beta release.",
        "operationId" : "analytics/create_mmm_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Create a request for a Marketing Mix Modeling (MMM) report",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/order_lines" : {
      "get" : {
        "description" : "List existing order lines associated with an ad account.",
        "operationId" : "order_lines/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get order lines",
        "tags" : [ "order_lines" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/order_lines/{order_line_id}" : {
      "get" : {
        "description" : "Get a specific existing order line associated with an ad account.",
        "operationId" : "order_lines/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get order line",
        "tags" : [ "order_lines" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions" : {
      "get" : {
        "description" : "List existing product group promotions associated with an ad account.\n\nInclude either ad_group_id or product_group_promotion_ids in your request.\n\n<b>Note:</b> ad_group_ids and product_group_promotion_ids are mutually exclusive parameters.\nOnly provide one. If multiple options are provided, product_group_promotion_ids takes precedence over ad_group_ids. If none are provided, the endpoint returns an error.",
        "operationId" : "product_group_promotions/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get product group promotions",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update multiple existing Product Group Promotions (by product_group_id)",
        "operationId" : "product_group_promotions/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update product group promotions",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Add one or more product groups from your catalog to an existing ad group. (Product groups added to an ad group are a 'product group promotion.')",
        "operationId" : "product_group_promotions/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create product group promotions",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}" : {
      "get" : {
        "description" : "Get a product group promotion by id",
        "operationId" : "product_group_promotions/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get a product group promotion by id",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, the furthest back you [...]",
        "operationId" : "product_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get product group analytics",
        "tags" : [ "product_group_promotions" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/reports" : {
      "get" : {
        "description" : "This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report. The link is valid for five minutes and the report is valid for one hour.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business [...]",
        "operationId" : "analytics/get_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get the account analytics report created by the async call",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Bus[...]",
        "operationId" : "analytics/create_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Create async request for an account analytics report",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/sandbox" : {
      "delete" : {
        "description" : "Delete an ad account and all the ads data associated with that account.\nA string message is returned indicating the status of the delete operation.\n\nNote: This endpoint is only allowed in the Pinterest API Sandbox (https://api-sandbox.pinterest.com/v5).\nGo to /docs/developer-tools/sandbox/ for more information.",
        "operationId" : "sandbox/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Delete ads data for ad account in API Sandbox",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/accounts" : {
      "get" : {
        "description" : "Get Salesforce account details including bill-to information to be used in insertion orders process for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_accounts/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get Salesforce account details including bill-to information.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders" : {
      "patch" : {
        "description" : "Edit insertion order through SSIO for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_insertion_order/edit",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Edit insertion order through SSIO.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create insertion order through SSIO for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_insertion_order/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create insertion order through SSIO.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders/status" : {
      "get" : {
        "description" : "Get insertion order status for account id <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_insertion_orders_status/get_by_ad_account",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get insertion order status by ad account id.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders/{pin_order_id}/status" : {
      "get" : {
        "description" : "Get insertion order status for pin order id <code>pin_order_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_insertion_orders_status/get_by_pin_order_id",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get insertion order status by pin order id.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/order_lines" : {
      "get" : {
        "description" : "Get Salesforce order lines for account id <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "operationId" : "ssio_order_lines/get_by_ad_account",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get Salesforce order lines by ad account id.",
        "tags" : [ "billing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/targeting_analytics" : {
      "get" : {
        "description" : "Get targeting analytics for an ad account.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage[...]",
        "operationId" : "ad_account_targeting_analytics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting analytics for an ad account",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/targeting_templates" : {
      "get" : {
        "description" : "Get a list of the targeting templates in the specified <code>ad_account_id</code>",
        "operationId" : "targeting_template/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List targeting templates",
        "tags" : [ "targeting_template" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "<p>Update the targeting template given advertiser ID and targeting template ID</p>",
        "operationId" : "targeting_template/update",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update targeting templates",
        "tags" : [ "targeting_template" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "<p>Targeting templates allow advertisers to save a set of targeting details including audience lists,\n keywords & interest, demographics, and placements to use more than once during the campaign creation process.</p>\n <p>Templates can be used to build out basic targeting criteria that you plan to use across campaigns and to reuse\n  performance targeting from prior campaigns for new campaigns.</p>",
        "operationId" : "targeting_template/create",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create targeting templates",
        "tags" : [ "targeting_template" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/templates" : {
      "get" : {
        "description" : "Gets all Templates associated with an ad account ID.",
        "operationId" : "templates/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List templates",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/templates/{template_id}/reports" : {
      "post" : {
        "description" : "This takes a template ID and an optional custom timeframe and constructs an asynchronous report based on the\ntemplate. It returns a token that you can use to download the report when it is ready.",
        "operationId" : "analytics/create_template_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Create async request for an analytics report using a template",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/terms_of_service" : {
      "get" : {
        "description" : "Get the text of the terms of service and see whether the advertiser has accepted the terms of service.",
        "operationId" : "terms_of_service/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get terms of service",
        "tags" : [ "terms_of_service" ],
        "x-sandbox" : "enabled",
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/advanced_auction/items/get" : {
      "post" : {
        "description" : "Get the bid options for a batch of retail catalog items.\n\nThe catalog must be owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a> By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</[...]",
        "operationId" : "advanced_auction_items_get/post",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read", "catalogs:read" ]
        } ],
        "summary" : "Get item bid options (POST)",
        "tags" : [ "advanced_auction" ],
        "x-ratelimit-category" : "advanced_auction_read",
        "x-sandbox" : "enabled"
      }
    },
    "/advanced_auction/items/submit" : {
      "post" : {
        "description" : "This endpoint supports multiple operations on a set of one or more bid options (bid price and bid adjustments for targeting categories) for retail catalog items. These advanced auction settings are applied in campaigns using objective_type `CATALOG_SALES` and ad groups using bid_strategy_type `MAX_BID`.\n\nThe catalog must be owned by the \"operation user_account\". <a href=\"/docs/api-features/modify-items-in-batch/\" target=\"_blank\">See detailed documentation here.</[...]",
        "operationId" : "advanced_auction_items_submit/post",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write", "catalogs:read" ]
        } ],
        "summary" : "Operate on item level bid options",
        "tags" : [ "advanced_auction" ],
        "x-ratelimit-category" : "advanced_auction_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards" : {
      "get" : {
        "description" : "Get a list of the boards owned by the \"operation user_account\" + group boards where this account is a collaborator\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\nOptional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.\n- If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) w[...]",
        "operationId" : "boards/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        }, {
          "client_credentials" : [ "boards:read" ]
        } ],
        "summary" : "List boards",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a board owned by the \"operation user_account\".\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}" : {
      "delete" : {
        "description" : "Delete a board owned by the \"operation user_account\".\n- Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a board owned by the operation user_account - or a group board that has been shared with this account.\n- Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        }, {
          "client_credentials" : [ "boards:read" ]
        } ],
        "summary" : "Get board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a board owned by the \"operating user_account\".\n- Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections" : {
      "get" : {
        "description" : "Get a list of all board sections from a board owned by the \"operation user_account\" - or a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        }, {
          "client_credentials" : [ "boards:read" ]
        } ],
        "summary" : "List board sections",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}" : {
      "delete" : {
        "description" : "Delete a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board section of a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/businesses/employers" : {
      "get" : {
        "description" : "Get all of the viewing user's business employers.",
        "operationId" : "get/business_employers",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "List business employers for user",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/businesses/invites" : {
      "patch" : {
        "description" : "Accept or decline invites or requests.",
        "operationId" : "respond_business_access_invites",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Accept or decline an invite/request",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/businesses/{business_id}/assets/{asset_id}/members" : {
      "get" : {
        "description" : "Get all the members the requesting business has granted access to on the given asset.",
        "operationId" : "business_asset_members/get",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get members with access to asset",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/assets/{asset_id}/partners" : {
      "get" : {
        "description" : "Get all the partners the requesting business has granted access to on the given asset.\nNote: If the asset has been shared with you, an empty array will be returned. This is because an asset shared with\nyou cannot be shared with a different partner.",
        "operationId" : "business_asset_partners/get",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get partners with access to asset",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/invites/assets/access" : {
      "post" : {
        "description" : "Assign asset permissions information to an existing invite/request. Can be used to:\n- Request access to a partner's asset. Note: This is only for when no existing partnership exists. If an existing\n  partnership exists, use \"Create a request to access an existing partner's assets\" to request access to your\n  partner's assets.\n    - invite_type=\"PARTNER_REQUEST\"\n- Invite a partner to access your business assets. Note: This is only for when there is no existing pa[...]",
        "operationId" : "create_asset_invites",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Update invite/request with an asset permission",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/requests/assets/access" : {
      "post" : {
        "description" : "Create a request to access an existing partner's assets with the specified permissions. The request will be sent to the partner for approval. The assets that can be requested are ad accounts and profiles.",
        "operationId" : "asset_access_requests/create",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Create a request to access an existing partner's assets.",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/members" : {
      "delete" : {
        "description" : "Terminate memberships between the specified members and your business.",
        "operationId" : "delete_business_membership",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Terminate business memberships",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get all members of the specified business.\nThe return response will include the member's business_role and assets they have access to if assets_summary=TRUE",
        "operationId" : "get/business_members",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get business members",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update a member's business role within the business.",
        "operationId" : "update/business_memberships",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Update member's business role",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/assets" : {
      "get" : {
        "description" : "Get all the assets the requesting business has access to. This includes assets the business owns and assets the business has access to through partnerships.",
        "operationId" : "business_assets/get",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "List business assets",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/members/{member_id}/assets" : {
      "get" : {
        "description" : "Get assets on which you assigned asset permissions to the given member. Can be used to:\n- get all assets, regardless of asset type or\n- get assets of one asset type by using the asset_type query.\nThe return response will include the permissions the member has to that asset and the asset type.",
        "operationId" : "business_member_assets/get",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get assets assigned to a member",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/members/assets/access" : {
      "delete" : {
        "description" : "Terminate multiple members' access to an asset.",
        "operationId" : "business_members_asset_access/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Delete member access to asset",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Grant multiple members access to assets and/or update multiple member's exisiting permissions to an asset.\nNote: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of the type PROFILE.\n",
        "operationId" : "business_members_asset_access/update",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Assign/Update member asset permissions",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/invites" : {
      "delete" : {
        "description" : "Cancel membership/partnership invites and/or requests.",
        "operationId" : "cancel_invites_or_requests",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Cancel invites/requests",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get the membership/partnership invites and/or requests for the authorized user.",
        "operationId" : "get/invites",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get invites/requests",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create batch invites or requests. Can create batch invites or requests as described below.\n- Invite members to join the business. This would required specifying the following:\n    - invite_type=\"MEMBER_INVITE\"\n    - business_role=\"EMPLOYEE\" OR business_role=\"BIZ_ADMIN\" (To learn more about business roles, visit\n    https://help.pinterest.com/en/business/article/profile-permissions-in-business-access.)\n    - members\n- Invite partners to access your business as[...]",
        "operationId" : "create_membership_or_partnership_invites",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Create invites or requests",
        "tags" : [ "business_access_invite" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/partners/assets" : {
      "delete" : {
        "description" : "Terminate multiple partners' access to an asset. If\n- partner_type=INTERNAL: You will terminate a partner's asset access to your business assets.\n- partner_type=EXTERNAL: You will terminate your own access to your partner's business assets.",
        "operationId" : "delete_partner_asset_access_handler_impl",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Delete partner access to asset",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Grant multiple partners access to assets and/or update multiple partner's exisiting permissions to an asset.\nIf your partner already had permissions on the asset, they will be overriden with the new permissions you assign to them.\nTo learn more about permission levels, visit https://help.pinterest.com/en/business/article/business-manager-overview\n\nNote: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be\napplicab[...]",
        "operationId" : "update_partner_asset_access_handler_impl",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Assign/Update partner asset permissions",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/partners/{partner_id}/assets" : {
      "get" : {
        "description" : "Can be used to get the business assets your partner has granted you access to or the business assets you have\ngranted your partner access to. If you specify:\n- partner_type=INTERNAL, you will retrieve your business assets that the partner has access to.\n- partner_type=EXTERNAL, you will retrieve the partner's business assets that the partner has granted you access to.",
        "operationId" : "business_partner_asset_access/get",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get assets assigned to a partner or assets assigned by a partner",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/partners" : {
      "delete" : {
        "description" : "Terminate partnerships between the specified partners and your business.\nNote: You may only batch terminate partners of the same partner type.",
        "operationId" : "delete_business_partners",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Terminate business partnerships",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get all partners of the specified business.\n\nIf the assets_summary=TRUE and:\n- partner_type=INTERNAL, the business assets returned are your business assets the partner has access to.\n- partner_type=EXTERNAL, the business assets returned are your partner's business assets the partner has granted you\n  access to.",
        "operationId" : "get/business_partners",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "Get business partners",
        "tags" : [ "business_access_relationships" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/audiences" : {
      "get" : {
        "description" : "Get a list of received audiences for the given business.",
        "operationId" : "shared_audiences_for_business/list",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "List received audiences for a business",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/audiences/shared/accounts" : {
      "get" : {
        "description" : "List all ad accounts and/or businesses that have access to a specific audience.\nThe audience must either be owned by an ad account in the requesting business, or it must have been shared with the requesting business.\nIf the requesting business is not the owner of the audience, only ad accounts owned by the requesting business will be returned.",
        "operationId" : "business_account_audiences_shared_accounts/list",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read" ]
        } ],
        "summary" : "List accounts with access to an audience owned by a business",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/audiences/ad_accounts/shared" : {
      "patch" : {
        "description" : "From a business, share a specific audience with other ad account(s), or revoke access to a previously shared audience. <ul> <li>If the business is the owner of the audience, it can share with any ad account within the same business hierarchy.</li> <li>If the business is the recipient of the audience, it can share with any of its owned ad accounts.</li> </ul> This endpoint is not available to all apps.<a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a[...]",
        "operationId" : "update_business_to_ad_account_shared_audience",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Update audience sharing from a business to ad accounts",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/audiences/businesses/shared" : {
      "patch" : {
        "description" : "From a business, share a specific audience with another business account, or revoke access to a previously shared audience. Only the audience owner can share the audience with other businesses, and the recipient business must be within the same business hierarchy.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.",
        "operationId" : "update_business_to_business_shared_audience",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:write" ]
        } ],
        "summary" : "Update audience sharing between businesses",
        "tags" : [ "audience_sharing" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/businesses/{business_id}/asset_groups" : {
      "delete" : {
        "description" : "Delete a batch of asset groups.",
        "operationId" : "asset_group/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Delete asset groups.",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update a batch of asset groups with the specified parameters.",
        "operationId" : "asset_group/update",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Update asset groups.",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Create a new asset group with the specified parameters.\n- An <a href=\"https://help.pinterest.com/en/business/article/asset-groups\">asset group</a> is a custom group of assets based on how you’d like to manage your accounts.",
        "operationId" : "asset_group/create",
        "security" : [ {
          "pinterest_oauth2" : [ "biz_access:read", "biz_access:write" ]
        } ],
        "summary" : "Create a new asset group.",
        "tags" : [ "business_access_assets" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs" : {
      "get" : {
        "description" : "Fetch catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busin[...]",
        "operationId" : "catalogs/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List catalogs",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a new catalog owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en[...]",
        "operationId" : "catalogs/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Create catalog",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/feeds" : {
      "get" : {
        "description" : "Fetch feeds owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/business[...]",
        "operationId" : "feeds/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        }, {
          "client_credentials" : [ "catalogs:read" ]
        } ],
        "summary" : "List feeds",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a new feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nPlease, be aware that \"default_country\"\nand \"default_locale\" are not required in the spec for forward compatibility\nbut for now the API will not accept requests without those fields.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</[...]",
        "operationId" : "feeds/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        }, {
          "client_credentials" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Create feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}" : {
      "delete" : {
        "description" : "Delete a feed owned by the \"operating user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busine[...]",
        "operationId" : "feeds/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        }, {
          "client_credentials" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Delete feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a single feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/bu[...]",
        "operationId" : "feeds/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        }, {
          "client_credentials" : [ "catalogs:read" ]
        } ],
        "summary" : "Get feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busine[...]",
        "operationId" : "feeds/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        }, {
          "client_credentials" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Update feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}/ingest" : {
      "post" : {
        "description" : "Ingest items for a given feed owned by the \"operation user_account\".\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">[...]",
        "operationId" : "feeds/ingest",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Ingest feed items",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}/processing_results" : {
      "get" : {
        "description" : "Fetch a feed processing results owned by the \"operation user_account\". Please note that for now the bookmark parameter is not functional and only the first page will be available until it is implemented in some release in the near future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use[...]",
        "operationId" : "feed_processing_results/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List feed processing results",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/processing_results/{processing_result_id}/item_issues" : {
      "get" : {
        "description" : "List item validation issues for a given feed processing result owned by the \"operation user_account\". Up to 20 random samples of affected items are returned for each error and warning code. Please note that for now query parameters 'item_numbers' and 'item_validation_issue' cannot be used simultaneously until it is implemented in some release in the future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an[...]",
        "operationId" : "items_issues/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List item issues",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/items" : {
      "get" : {
        "deprecated" : true,
        "description" : "Get the items of the catalog owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \[...]",
        "operationId" : "items/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Get the items of the catalog owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \[...]",
        "operationId" : "items/post",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items (POST)",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/items/batch" : {
      "post" : {
        "description" : "This endpoint supports multiple operations on a set of one or more catalog items owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accoun[...]",
        "operationId" : "items_batch/post",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        }, {
          "client_credentials" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Operate on item batch",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/items/batch/{batch_id}" : {
      "get" : {
        "description" : "Get a single catalogs items batch owned by the \"operating user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as [...]",
        "operationId" : "items_batch/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        }, {
          "client_credentials" : [ "catalogs:read" ]
        } ],
        "summary" : "Get item batch status",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/product_groups/multiple" : {
      "delete" : {
        "description" : "Delete product groups owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/e[...]",
        "operationId" : "catalogs_product_groups/delete_many",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Delete product groups",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create product group to use in Catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://he[...]",
        "operationId" : "catalogs_product_groups/create_many",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Create product groups",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/product_groups" : {
      "get" : {
        "description" : "Get a list of product groups for a given Catalogs Feed Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a[...]",
        "operationId" : "catalogs_product_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List product groups",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create product group to use in Catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://he[...]",
        "operationId" : "catalogs_product_groups/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Create product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}" : {
      "delete" : {
        "description" : "Delete a product group owned by the \"operation user_account\" from being in use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href[...]",
        "operationId" : "catalogs_product_groups/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Delete product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a singe product group for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the follow[...]",
        "operationId" : "catalogs_product_groups/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update product group owned by the \"operation user_account\" to use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://he[...]",
        "operationId" : "catalogs_product_groups/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Update single product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/product_counts" : {
      "get" : {
        "description" : "Get a product counts for a given Catalogs Product Group owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a h[...]",
        "operationId" : "catalogs_product_groups/product_counts_get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get product counts",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/products" : {
      "get" : {
        "description" : "Get a list of product pins for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the follo[...]",
        "operationId" : "catalogs_product_group_pins/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "catalogs:read", "pins:read" ]
        } ],
        "summary" : "List products by product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/products/get_by_product_group_filters" : {
      "post" : {
        "description" : "List products Pins owned by the \"operation user_account\" that meet the criteria specified in the Catalogs Product Group Filter given in the request.\n- This endpoint has been implemented in POST to allow for complex filters. This specific POST endpoint is designed to be idempotent.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad[...]",
        "operationId" : "products_by_product_group_filter/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "catalogs:read", "pins:read" ]
        } ],
        "summary" : "List products by filter",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "enabled"
      }
    },
    "/catalogs/reports" : {
      "get" : {
        "description" : "This returns a URL to a report given a token returned from <a href='/docs/api/v5/#operation/reports/create'>Build catalogs report</a>. You can use the URL to download the report.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\[...]",
        "operationId" : "reports/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs report",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Async request to create a report of the catalog owned by the \"operation user_account\". This endpoint generates a report upon receiving the first approved request of the day. Any following requests with identical parameters will yield the same report even if data has changed.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accoun[...]",
        "operationId" : "reports/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Build catalogs report",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/catalogs/reports/stats" : {
      "get" : {
        "description" : "List aggregated numbers of issues for a catalog owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"ht[...]",
        "operationId" : "reports/stats",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List report stats",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read",
        "x-sandbox" : "disabled"
      }
    },
    "/integrations/commerce" : {
      "post" : {
        "description" : "Create commerce integration metadata to link an external business ID with a Pinterest merchant & ad account.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations_commerce/post",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Create commerce integration",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/integrations/commerce/{external_business_id}" : {
      "delete" : {
        "description" : "Delete commerce integration metadata for the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations_commerce/del",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Delete commerce integration",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get commerce integration metadata associated with the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations_commerce/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get commerce integration",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      },
      "patch" : {
        "description" : "Update commerce integration metadata for the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations_commerce/patch",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Update commerce integration",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "disabled"
      }
    },
    "/integrations/logs" : {
      "post" : {
        "description" : "This endpoint receives batched logs from integration applications on partner platforms.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations_logs/post",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:write" ]
        } ],
        "summary" : "Receives batched logs from integration applications.",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_write",
        "x-sandbox" : "enabled"
      }
    },
    "/integrations" : {
      "get" : {
        "description" : "Get integration metadata list.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations/get_list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get integration metadata list",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/integrations/{id}" : {
      "get" : {
        "description" : "Get integration metadata by ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "operationId" : "integrations/get_by_id",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get integration metadata",
        "tags" : [ "integrations" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "disabled"
      }
    },
    "/media" : {
      "get" : {
        "description" : "List media uploads filtered by given parameters.\n\n<strong><a href='/docs/api-features/creating-boards-and-pins/#creating-video-pins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/list",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "List media uploads",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Register your intent to upload media\n\nThe response includes all of the information needed to upload the media\nto Pinterest.\n\nTo upload the media, make an HTTP POST request (using <tt>curl</tt>, for\nexample) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header\nvalue. Send the media file's contents as the request's <tt>file</tt>\nparameter and also include all of the parameters from\n<tt>upload_parameters</tt>.\n\n<strong><a href='/docs/api-features/creatin[...]",
        "operationId" : "media/create",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "pins:write" ]
        } ],
        "summary" : "Register media upload",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/media/{media_id}" : {
      "get" : {
        "description" : "Get details for a registered media upload, including its current status.\n\n<strong><a href='/docs/api-features/creating-boards-and-pins/#creating-video-pins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/get",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "Get media upload details",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/oauth/token" : {
      "post" : {
        "description" : "Generate an OAuth access token by using an authorization code or a refresh token.\n\nIMPORTANT: You need to start the OAuth flow via www.pinterest.com/oauth before calling this endpoint (or have an existing refresh token).\n\nSee <a href='/docs/getting-started/authentication-and-scopes/'>Authentication</a> for more.\n\n<strong>Parameter <i>refresh_on</i> and its corresponding response type <i>everlasting_refresh</i> are now available to all apps! Later this year, continu[...]",
        "operationId" : "oauth/token",
        "security" : [ {
          "basic" : [ ]
        } ],
        "summary" : "Generate OAuth access token",
        "tags" : [ "oauth" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/pins" : {
      "get" : {
        "description" : "Get a list of the Pins owned by the \"operation user_account\".\n  - By default, the \"operation user_account\" is the token user_account.\n  - All Pins owned by the \"operation user_account\" are included, regardless of who owns the board they are on.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n\nDisclaimer: there are known performance issues when filtering by field <code>creative_type</cod[...]",
        "operationId" : "pins/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "post" : {
        "description" : "Create a Pin on a board or board section owned by the \"operation user_account\".\n\nNote: If the current \"operation user_account\" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).\n\n- This function i[...]",
        "operationId" : "pins/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Create Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/pins/{pin_id}" : {
      "delete" : {
        "description" : "Delete a Pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of[...]",
        "operationId" : "pins/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Delete Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      },
      "get" : {
        "description" : "Get a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the[...]",
        "operationId" : "pins/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      },
      "patch" : {
        "description" : "Update a pin owned by the \"operating user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busines[...]",
        "operationId" : "pins/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Update Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/pins/{pin_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=\"/docs/api/v5/#operation/ad_accounts/list\">List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must[...]",
        "operationId" : "pins/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin analytics",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/pins/analytics" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>\n\nGet analytics for multiple pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- The maximum number of pins supported in a single request is 100.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an[...]",
        "operationId" : "multi_pins/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        }, {
          "client_credentials" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get multiple Pin analytics",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/pins/{pin_id}/save" : {
      "post" : {
        "description" : "Save a Pin on a board or board section owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.[...]",
        "operationId" : "pins/save",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Save Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/ad_account_countries" : {
      "get" : {
        "description" : "Get Ad Accounts countries",
        "operationId" : "ad_account_countries/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad accounts countries",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/delivery_metrics" : {
      "get" : {
        "description" : "Get the definitions for ads and organic metrics available across both synchronous and asynchronous report endpoints.\nThe `display_name` attribute will match how the metric is named in our native tools like Ads Manager.\nSee <a href='/docs/api-features/analytics-overview/'>Organic Analytics</a> and <a href='/docs/api-features/ads-reporting/'>Ads Analytics</a> for more information.",
        "operationId" : "delivery_metrics/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read", "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get available metrics' definitions",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/lead_form_questions" : {
      "get" : {
        "description" : "Get a list of all lead form question type names. Some questions might not be used.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>",
        "operationId" : "lead_form_questions/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get lead form questions",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/metrics_ready_state" : {
      "get" : {
        "description" : "Learn whether conversion or non-conversion metrics are finalized and ready to query.",
        "operationId" : "metrics_ready_state/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get metrics ready state",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_analytics",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/targeting/interests/{interest_id}" : {
      "get" : {
        "description" : "<p>Get details of a specific interest given interest ID.</p> <p>Click <a href=\"https://docs.google.com/spreadsheets/d/1HxL-0Z3p2fgxis9YBP2HWC3tvPrs1hAuHDRtH-NJTIM/edit#gid=118370875\" target=\"_blank\">here</a> for a spreadsheet listing interests and their IDs.</p>",
        "operationId" : "interest_targeting_options/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get interest details",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/resources/targeting/{targeting_type}" : {
      "get" : {
        "description" : "<p>You can use targeting values in ads placement to define your intended audience. </p> <p>Targeting metrics are organized around targeting specifications.</p> <p>For more information on ads targeting, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>.</p>\n<p><b>Sample return:</b></p> <pre class=\"literal-block\"> [{&quot;36313&quot;: &quot;Australia: Moreton Bay - Nort[...]",
        "operationId" : "targeting_options/get",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get targeting options",
        "tags" : [ "resources" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/search/boards" : {
      "get" : {
        "description" : "Search for boards for the \"operation user_account\". This includes boards of all board types.\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "operationId" : "search_user_boards/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:read_secret" ]
        }, {
          "client_credentials" : [ "boards:read", "boards:read_secret" ]
        } ],
        "summary" : "Search user's boards",
        "tags" : [ "search" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/search/pins" : {
      "get" : {
        "description" : "Search for pins for the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "operationId" : "search_user_pins/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:read_secret", "pins:read", "pins:read_secret" ]
        } ],
        "summary" : "Search user's Pins",
        "tags" : [ "search" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/search/partner/pins" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>\n\nGet the top 10 Pins by a given search term.",
        "operationId" : "search_partner_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Search pins by a given search term",
        "tags" : [ "search" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/terms/related" : {
      "get" : {
        "description" : "Get a list of terms logically related to each input term. <p/>\nExample: the term 'workout' would list related terms like 'one song workout', 'yoga workout', 'workout motivation', etc.",
        "operationId" : "terms_related/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List related terms",
        "tags" : [ "terms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/terms/suggested" : {
      "get" : {
        "description" : "Get popular search terms that begin with your input term. <p/>\nExample: 'sport' would return popular terms like 'sports bar' and 'sportswear', but not 'motor sports' since the phrase does not begin with the given term.",
        "operationId" : "terms_suggested/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List suggested terms",
        "tags" : [ "terms" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/trends/keywords/{region}/top/{trend_type}" : {
      "get" : {
        "description" : "<p>Get the top trending search keywords among the Pinterest user audience.</p> <p>Trending keywords can be used to inform ad targeting, budget strategy, and creative decisions about which products and Pins will resonate with your audience.</p> <p>Geographic, demographic and interest-based filters are available to narrow down to the top trends among a specific audience. Multiple trend types are supported that can be used to identify newly-popular, evergreen or seasonal ke[...]",
        "operationId" : "trending_keywords/list",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "List trending keywords",
        "tags" : [ "keywords" ],
        "x-ratelimit-category" : "trends_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account" : {
      "get" : {
        "description" : "Get account information for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "operationId" : "user_account/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/analytics" : {
      "get" : {
        "description" : "Get analytics for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/analytics/top_pins" : {
      "get" : {
        "description" : "Gets analytics data about a user's top pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics/top_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "user_accounts:read" ]
        }, {
          "client_credentials" : [ "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get user account top pins analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/analytics/top_video_pins" : {
      "get" : {
        "description" : "Gets analytics data about a user's top video pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics/top_video_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "user_accounts:read" ]
        }, {
          "client_credentials" : [ "pins:read", "user_accounts:read" ]
        } ],
        "summary" : "Get user account top video pins analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/businesses" : {
      "get" : {
        "description" : "Get a list of your linked business accounts.",
        "operationId" : "linked_business_accounts/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "List linked businesses",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/followers" : {
      "get" : {
        "description" : "Get a list of your followers.",
        "operationId" : "followers/list",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "List followers",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "ads_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/following" : {
      "get" : {
        "description" : "Get a list of who a certain user follows.",
        "operationId" : "user_following/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "List following",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/following/boards" : {
      "get" : {
        "description" : "Get a list of the boards a user follows. The request returns a board summary object array.",
        "operationId" : "boards_user_follows/list",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "List following boards",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/following/{username}" : {
      "post" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/beta-and-advanced-access/'>Learn more</a>.</strong>\n\nUse this request, as a signed-in user, to follow another user.",
        "operationId" : "follow_user/update",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:write" ]
        } ],
        "summary" : "Follow user",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "enabled"
      }
    },
    "/user_account/websites" : {
      "delete" : {
        "description" : "Unverifu a website verified by the signed-in user.",
        "operationId" : "unverify_website/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:write" ]
        } ],
        "summary" : "Unverify website",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "disabled"
      },
      "get" : {
        "description" : "Get user websites, claimed or not",
        "operationId" : "user_websites/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user websites",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      },
      "post" : {
        "description" : "Verify a website as a signed-in user.",
        "operationId" : "verify_website/update",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:write" ]
        } ],
        "summary" : "Verify website",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_write",
        "x-sandbox" : "disabled"
      }
    },
    "/user_account/websites/verification" : {
      "get" : {
        "description" : "Get verification code for user to install on the website to claim it.",
        "operationId" : "website_verification/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user verification code for website claiming",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "disabled"
      }
    },
    "/users/{username}/interests/follow" : {
      "get" : {
        "description" : "Get a list of a user's following interests in one place.",
        "operationId" : "user_account/followed_interests",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        }, {
          "client_credentials" : [ "user_accounts:read" ]
        } ],
        "summary" : "List following interests",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read",
        "x-sandbox" : "enabled"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "pinterest_oauth2" : {
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://www.pinterest.com/oauth/",
            "scopes" : {
              "ads:read" : "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write" : "Create, update, or delete ads, ad groups, campaigns etc.",
              "billing:read" : "See all of your billing data, billing profile, etc.",
              "billing:write" : "Create, update, or delete billing data, billing profiles, etc.",
              "biz_access:read" : "See business access data",
              "biz_access:write" : "Create, update, or delete business access data",
              "boards:read" : "See your public boards, including group boards you join",
              "boards:read_secret" : "See your secret boards",
              "boards:write" : "Create, update, or delete your public boards",
              "boards:write_secret" : "Create, update, or delete your secret boards",
              "catalogs:read" : "See all of your catalogs data",
              "catalogs:write" : "Create, update, or delete your catalogs data",
              "pins:read" : "See your public Pins",
              "pins:read_secret" : "See your secret Pins",
              "pins:write" : "Create, update, or delete your public Pins",
              "pins:write_secret" : "Create, update, or delete your secret Pins",
              "user_accounts:read" : "See your user accounts and followers",
              "user_accounts:write" : "Update your user accounts and followers"
            },
            "tokenUrl" : "https://api.pinterest.com/v5/oauth/token"
          }
        },
        "type" : "oauth2"
      },
      "conversion_token" : {
        "description" : "This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).",
        "scheme" : "bearer",
        "type" : "http"
      },
      "basic" : {
        "scheme" : "basic",
        "type" : "http"
      },
      "client_credentials" : {
        "flows" : {
          "clientCredentials" : {
            "scopes" : {
              "ads:read" : "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write" : "Create, update, or delete ads, ad groups, campaigns etc.",
              "billing:read" : "See all of your billing data, billing profile, etc.",
              "billing:write" : "Create, update, or delete billing data, billing profiles, etc.",
              "biz_access:read" : "See business access data",
              "biz_access:write" : "Create, update, or delete business access data",
              "boards:read" : "See your public boards, including group boards you join",
              "boards:read_secret" : "See your secret boards",
              "boards:write" : "Create, update, or delete your public boards",
              "boards:write_secret" : "Create, update, or delete your secret boards",
              "catalogs:read" : "See all of your catalogs data",
              "catalogs:write" : "Create, update, or delete your catalogs data",
              "pins:read" : "See your public Pins",
              "pins:read_secret" : "See your secret Pins",
              "pins:write" : "Create, update, or delete your public Pins",
              "pins:write_secret" : "Create, update, or delete your secret Pins",
              "user_accounts:read" : "See your user accounts and followers",
              "user_accounts:write" : "Update your user accounts and followers"
            },
            "tokenUrl" : "https://api.pinterest.com/v3/oauth/access_token/"
          }
        },
        "type" : "oauth2"
      }
    }
  },
  "x-tagGroups" : [ {
    "name" : "Pin and Boards",
    "tags" : [ "pins", "boards", "media", "aggregated_comments", "aggregated_pin_data", "user_account" ]
  }, {
    "name" : "Campaign Management",
    "tags" : [ "ad_accounts", "campaigns", "ad_groups", "ads", "product_group_promotions", "bulk" ]
  }, {
    "name" : "Targeting",
    "tags" : [ "audiences", "customer_lists", "keywords", "targeting_template", "audience_insights", "audience_sharing" ]
  }, {
    "name" : "Ad Formats",
    "tags" : [ "lead_forms", "lead_ads", "leads_export" ]
  }, {
    "name" : "Billing",
    "tags" : [ "billing", "order_lines", "terms_of_service" ]
  }, {
    "name" : "Business Access",
    "tags" : [ "business_access_assets", "business_access_invite", "business_access_relationships" ]
  }, {
    "name" : "Conversions",
    "tags" : [ "conversion_events", "conversion_tags" ]
  }, {
    "name" : "Others",
    "tags" : [ "advanced_auction", "integrations", "oauth", "resources", "search", "terms" ]
  }, {
    "name" : "Shopping",
    "tags" : [ "catalogs" ]
  } ]
}
