{
  "openapi" : "3.0.3",
  "info" : {
    "contact" : {
      "email" : "pinterest-api@pinterest.com",
      "name" : "Pinterest, Inc.",
      "url" : "https://developers.pinterest.com/"
    },
    "description" : "Pinterest's REST API",
    "license" : {
      "name" : "MIT",
      "url" : "https://spdx.org/licenses/MIT"
    },
    "termsOfService" : "https://developers.pinterest.com/terms/",
    "title" : "Pinterest REST API",
    "version" : "5.3.0"
  },
  "servers" : [ {
    "url" : "https://api.pinterest.com/v5"
  } ],
  "tags" : [ {
    "description" : "View analytical information about advertising.\n\n\nNote: If the current operation_user_account (defined by the access token)\nhas access to another user's Ad Accounts via\n<a href='/docs/api/v5/#tag/Understanding-business-access'>Pinterest Business Access</a>,\nyou can modify your request to use the current operation_user_account's\npermissions to those Ad Accounts by including the ad_account_id in the path\nparameters for the request (e.g. .../?ad_account_id=12345&...).",
    "name" : "ad_accounts"
  }, {
    "description" : "View, create, update, or delete information about boards.",
    "name" : "boards"
  }, {
    "description" : "Manage information about shopping product catalogs and items.",
    "name" : "catalogs"
  }, {
    "description" : "Register and manage media uploads.",
    "name" : "media"
  }, {
    "description" : "Generating and refreshing OAuth access tokens.",
    "name" : "oauth"
  }, {
    "description" : "View, create, update, or delete information about Pins.",
    "name" : "pins"
  }, {
    "description" : "Read-only information about user accounts associated with a given access token.",
    "name" : "user_account"
  } ],
  "paths" : {
    "/oauth/token" : {
      "post" : {
        "description" : "Generate an OAuth access token by using an authorization code or a refresh token.\n\nSee <a href='/docs/api/v5/#tag/Authentication'>Authentication</a> for more.",
        "operationId" : "oauth/token",
        "security" : [ { } ],
        "summary" : "Generate OAuth access token",
        "tags" : [ "oauth" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/user_account" : {
      "get" : {
        "description" : "Get account information for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/api/v5/#tag/Understanding-business-access'>Understanding Business Access</a> for more information.",
        "operationId" : "user_account/get",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/user_account/analytics" : {
      "get" : {
        "description" : "Get analytics for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "operationId" : "user_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "user_accounts:read" ]
        } ],
        "summary" : "Get user account analytics",
        "tags" : [ "user_account" ],
        "x-ratelimit-category" : "org_analytics"
      }
    },
    "/pins" : {
      "post" : {
        "description" : "Create a Pin on a board or board section owned by the \"operation user_account\".\n\nNote: If the current \"operation user_account\" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).\n\n- This function i[...]",
        "operationId" : "pins/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Create Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/pins/{pin_id}" : {
      "delete" : {
        "description" : "Delete a Pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "pins/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write", "pins:read", "pins:write" ]
        } ],
        "summary" : "Delete Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_write"
      },
      "get" : {
        "description" : "Get a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the[...]",
        "operationId" : "pins/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/pins/{pin_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=\"https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list\">List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do t[...]",
        "operationId" : "pins/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "Get Pin analytics",
        "tags" : [ "pins" ],
        "x-ratelimit-category" : "org_analytics"
      }
    },
    "/boards" : {
      "get" : {
        "description" : "Get a list of the boards owned by the \"operation user_account\" + group boards where this account is a collaborator\n\nOptional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.\n- If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.",
        "operationId" : "boards/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "List boards",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read"
      },
      "post" : {
        "description" : "Create a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/boards/{board_id}" : {
      "delete" : {
        "description" : "Delete a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      },
      "get" : {
        "description" : "Get a board owned by the operation user_account - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/get",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "Get board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read"
      },
      "patch" : {
        "description" : "Update a board owned by the \"operating user_account\".",
        "operationId" : "boards/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/boards/{board_id}/sections" : {
      "get" : {
        "description" : "Get a list of all board sections from a board owned by the \"operation user_account\" - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read" ]
        } ],
        "summary" : "List board sections",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read"
      },
      "post" : {
        "description" : "Create a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/create",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Create board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/boards/{board_id}/sections/{section_id}" : {
      "delete" : {
        "description" : "Delete a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Delete board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      },
      "patch" : {
        "description" : "Update a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/update",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "boards:write" ]
        } ],
        "summary" : "Update board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/boards/{board_id}/sections/{section_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board section of a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "board_sections/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board section",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/boards/{board_id}/pins" : {
      "get" : {
        "description" : "Get a list of the Pins on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "operationId" : "boards/list_pins",
        "security" : [ {
          "pinterest_oauth2" : [ "boards:read", "pins:read" ]
        } ],
        "summary" : "List Pins on board",
        "tags" : [ "boards" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/media" : {
      "get" : {
        "description" : "List media uploads filtered by given parameters.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/list",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "List media uploads",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read"
      },
      "post" : {
        "description" : "Register your intent to upload media\n\nThe response includes all of the information needed to upload the media\nto Pinterest.\n\nTo upload the media, make an HTTP POST request (using <tt>curl</tt>, for\nexample) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header\nvalue. Send the media file's contents as the request's <tt>file</tt>\nparameter and also include all of the parameters from\n<tt>upload_parameters</tt>.\n\n<strong><a href='/docs/solutions/content-ap[...]",
        "operationId" : "media/create",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read", "pins:write" ]
        } ],
        "summary" : "Register media upload",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_write"
      }
    },
    "/media/{media_id}" : {
      "get" : {
        "description" : "Get details for a registered media upload, including its current status.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "operationId" : "media/get",
        "security" : [ {
          "pinterest_oauth2" : [ "pins:read" ]
        } ],
        "summary" : "Get media upload details",
        "tags" : [ "media" ],
        "x-ratelimit-category" : "org_read"
      }
    },
    "/ad_accounts" : {
      "get" : {
        "description" : "Get a list of the ad_accounts that the \"operation user_account\" has access to.\n- This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>.",
        "operationId" : "ad_accounts/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad accounts",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ad_account/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad account analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns" : {
      "get" : {
        "description" : "Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "campaigns/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List campaigns",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "campaigns/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get campaign analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups" : {
      "get" : {
        "description" : "Get a list of the ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ad_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ad groups",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ad_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad group analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/ad_accounts/{ad_account_id}/ads" : {
      "get" : {
        "description" : "Get a list of the ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ads/list",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "List ads",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "ads/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get ad analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/ad_accounts/{ad_account_id}/product_groups/analytics" : {
      "get" : {
        "description" : "Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId" : "product_groups/analytics",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get product group analytics",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/ad_accounts/{ad_account_id}/reports" : {
      "get" : {
        "description" : "This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report and it's valid for an hour.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager."[...]",
        "operationId" : "analytics/get_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Get the account analytics report created by the async call",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      },
      "post" : {
        "description" : "This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Bus[...]",
        "operationId" : "analytics/create_report",
        "security" : [ {
          "pinterest_oauth2" : [ "ads:read" ]
        } ],
        "summary" : "Create async request for an account analytics report",
        "tags" : [ "ad_accounts" ],
        "x-ratelimit-category" : "ads_analytics"
      }
    },
    "/catalogs/feeds" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nFetch feeds owned by the \"operating user_account\".",
        "operationId" : "feeds/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List feeds",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      },
      "post" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nCreate a new feed owned by the \"operating user_account\".",
        "operationId" : "feeds/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Create feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      }
    },
    "/catalogs/feeds/{feed_id}" : {
      "delete" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nDelete a feed owned by the \"operating user_account\".",
        "operationId" : "feeds/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Delete feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      },
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nGet a single feed owned by the \"operating user_account\".",
        "operationId" : "feeds/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      },
      "patch" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nUpdate a feed owned by the \"operating user_account\".",
        "operationId" : "feeds/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Update feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      }
    },
    "/catalogs/feeds/{feed_id}/processing_results" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nFetch a feed processing results owned by the owner user account.",
        "operationId" : "feed_processing_results/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "List processing results for a given feed",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      }
    },
    "/catalogs/items" : {
      "get" : {
        "description" : "Get the items of the catalog created by the \"operating user_account\"",
        "operationId" : "items/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      }
    },
    "/catalogs/items/batch/{batch_id}" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nGet a single catalogs items batch created by the \"operating user_account\".",
        "operationId" : "items_batch/get",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get catalogs items batch",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      }
    },
    "/catalogs/items/batch" : {
      "post" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nThis endpoint supports multiple operations on a set of one or more catalog items.",
        "operationId" : "items_batch/post",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read", "catalogs:write" ]
        } ],
        "summary" : "Perform an operation on an item batch",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      }
    },
    "/catalogs/product_groups/{product_group_id}" : {
      "delete" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nDelete a product group from being in use in Catalogs.",
        "operationId" : "catalogs_product_groups/delete",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Delete product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      },
      "patch" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nUpdate product group to use in Catalogs.",
        "operationId" : "catalogs_product_groups/update",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Update product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      }
    },
    "/catalogs/product_groups" : {
      "get" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nGet a list of product groups for a given Catalogs Feed Id.",
        "operationId" : "catalogs_product_groups/list",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:read" ]
        } ],
        "summary" : "Get product groups list",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_read"
      },
      "post" : {
        "description" : "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nCreate product group to use in Catalogs.",
        "operationId" : "catalogs_product_groups/create",
        "security" : [ {
          "pinterest_oauth2" : [ "catalogs:write" ]
        } ],
        "summary" : "Create product group",
        "tags" : [ "catalogs" ],
        "x-ratelimit-category" : "catalogs_write"
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "pinterest_oauth2" : {
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://www.pinterest.com/oauth/",
            "scopes" : {
              "ads:read" : "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write" : "Create, update, or delete ads, ad groups, campaigns etc.",
              "boards:read" : "See your public boards, including group boards you join",
              "boards:read_secret" : "See your secret boards",
              "boards:write" : "Create, update, or delete your public boards",
              "boards:write_secret" : "Create, update, or delete your secret boards",
              "catalogs:read" : "See all of your catalogs data",
              "catalogs:write" : "Create, update, or delete your catalogs data",
              "pins:read" : "See your public Pins",
              "pins:read_secret" : "See your secret Pins",
              "pins:write" : "Create, update, or delete your public Pins",
              "pins:write_secret" : "Create, update, or delete your secret Pins",
              "user_accounts:read" : "See your user accounts"
            },
            "tokenUrl" : "https://api.pinterest.com/v5/oauth/token"
          }
        },
        "type" : "oauth2"
      },
      "basic" : {
        "scheme" : "basic",
        "type" : "http"
      }
    }
  }
}